---

- name: shutdown all lights and players
  hosts: players
  tags: stop
  become: true

  tasks:
    - name: turn off leds
      shell:
        cmd: python3 stop.py
        chdir: /home/pi/synch
    - name: shutdown
      community.general.shutdown:
        delay: 0

- name: reboot all players
  hosts: players
  tags: reboot
  become: true

  tasks:
    - name: turn off leds
      shell:
        cmd: python3 stop.py
        chdir: /home/pi/synch
    - name: reboot (wait 10sec)
      reboot:
        reboot_timeout: 10

